name: On PR - Native - Builder Substrate

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - native/builder-substrate.Dockerfile
      - Makefile

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64, epoch-arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Test Build Docker Image
        run: make native-aarch64-bs
