name: On PR - Native - Builder Substrate

on:
  pull_request:
    branches:
      - main
    paths:
      - native/builder-substrate.Dockerfile

jobs:
  build:
    runs-on:
      - self-hosted
      - epoch-arm64
    steps:
      - uses: actions/checkout@v3
      - name: Test Build Docker Image
        run: make native-aarch64-bs
